spring:
  application:
    name: jwts
  profiles:
    active: prod # muda para 'prod' em ambiente de produção

server:
  port: 8080
  servlet:
    context-path: /
  swagger-ui:
    path: /swagger-ui.html
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-stacktrace: never

jwt:
  jwtSecret: Y2hhdmUtc2VndXJhLXBhcmEtZ2VyYWNhby1kZS10b2tlbnM=
  jwtAccessExpirationMs: 900000 # 15 min
  jwtRefreshExpirationMs: 86400000 # 1 dia

app:
  frontend:
    url: http://localhost:4200
  environment: ${APP_ENVIRONMENT:dev}

logging:
  level:
    org.springframework.security: DEBUG
