server:
  port: 8080

spring:
  application:
    name: jwts
  datasource:
    url: jdbc:h2:mem:testdb # banco em memória (troque por jdbc:h2:file:./data/testdb para arquivo)
    driver-class-name: org.h2.Driver
    username: sampleuser
    password: mysecretpassword
  h2:
    console:
      enabled: true # habilita console web
      path: /h2-console # URL para acessar no navegador (http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: update # cria/atualiza tabelas automaticamente (create, update, validate, none)
    show-sql: true # loga as queries SQL no console
    properties:
      hibernate:
        format_sql: true

jwt:
  jwtSecret: Y2hhdmUtc2VndXJhLXBhcmEtZ2VyYWNhby1kZS10b2tlbnM=
  jwtAccessExpirationMs: 900000 # 15 min
  jwtRefreshExpirationMs: 86400000 # 1 dia

app:
  environment: dev

logging:
  level:
    org.springframework.security: DEBUG